return {
 "Abyssal Specter Rod",
 "Arctic Rod",
 "Aurora Rod",
 "Avalanche Rod",
 "Carbon Rod",
 "Champions Rod",
 "Crystalized Rod",
 "Depthseeker Rod",
 "Destiny Rod",
 "Fast Rod",
 "Fortune Rod",
 "Ice Warpers Rod",
 "Kings Rod",
 "Kraken Rod",
 "Long Rod",
 "Lucky Rod",
 "Magnet Rod",
 "Midas Rod",
 "Mythical Rod",
 "Nocturnal Rod",
 "Plastic Rod",
 "Poseidon Rod",
 "Rapid Rod",
 "Reinforced Rod",
 "Scurvy Rod",
 "Steady Rod",
 "Summit Rod",
 "Tempest Rod",
 "Tempest Rod",
 "Training Rod",
 "Trident Rod",
 "Zeus Rod"
}

